language: php
os:
- linux
script: echo test
before_deploy:
  - zip -r latest *
  - test -d dpl_cd_upload || mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $awskey
    secret_access_key:
      secure: $awskey_secure
    local_dir: dpl_cd_upload
    skip_cleanup: true
    region: us-east-2
    on:
      branch: master
    bucket: "roger-test-codedeploy"
  - provider: codedeploy
    access_key_id: $awskey
    secret_access_key:
      secure: $awskey_secure
    bucket: "roger-test-codedeploy"
    key: latest.zip
    application: 0608-deploy
    deployment_group: 0608-deploy-group
    region: us-east-2
    on:
      branch: master
